### ISSUE TITLE
trying to download a video - and getting error

### ISSUE THREAD

**Issue by hetzbh** [1024mb/TT_downloader#1]
Hi
Just found your script and the part of --output-name is not clear IMHO (I'll be happy if you could add an example in your readme file please)

When trying to run with a tiktok example video, I get this error:

<code>
./TT_downloader.py --output-name "%author_id%" https://www.tiktok.com/@nailzkatkat/video/7202395976890469678
Traceback (most recent call last):
  File "/home/hetz/TT_downloader/./TT_downloader.py", line 514, in <module>
    main()
  File "/home/hetz/TT_downloader/./TT_downloader.py", line 98, in main
    if os.path.isdir(archive_file):
  File "/usr/lib/python3.9/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
</code>

**Comment by 1024mb** [comment]
The problem was that I always assumed `--archive-file` was specified, I've added some checks, it should work now.
I've also updated the readme, hopefully it's clearer.
